Swagger2Markup/swagger2markup

- src/main/java/io/github/robwin/swagger2markup/Swagger2MarkupConverter.java
- src/main/java/io/github/robwin/swagger2markup/builder/document/DefinitionsDocument.java
- src/test/java/io/github/robwin/swagger2markup/Swagger2MarkupConverterTest.java
I needed the ability to write the object definitions to separate files, with one file for each object.  This PR is a proposed implementation that doesn't break backward compatibility.
The only change in terms of usage is the addition of a `withSplitDescriptions()` method to `Swagger2MarkupConverter` to inform the converter that it should also generate separate files.  The rest of the changes are mainly internal refactoring to allow the use of multiple writers since we need to create a new one every time we encounter a new object definition.
> Adding possibility to write object definitions to separate files.

- src/main/java/io/github/robwin/swagger2markup/builder/document/DefinitionsDocument.java
- src/test/java/io/github/robwin/swagger2markup/Swagger2MarkupConverterTest.java
- src/test/resources/json/swagger.json
Currently, if you have a composed definition (using the `allOf` device), no documentation is generated for that definition other than the header and description.  This is because the current `definition` code does not take into account `$ref`s or composition.
This adds support for both reference models and composed models.  The composition logic could likely be improved to provide better documentation for the composition (i.e. - where the definition came from, etc.), but for this improvement just flattens the composed model in the documentation.  I see this is a fine compromise given that's how the endpoint will behave, anyway.
Sorry/not-sorry for modifying the test suite's `swagger.json` - I wanted to make sure this didn't break any of the existing functionality.
Let me know what you …
> Adding support for composed model definitions

- build.gradle
There's a breaking change in Gradle 2.5 and it won't work with the dependency-management-plugin 0.5.1.RELEASE See: https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/54
I have updated the dependency-management.plugin to 0.5.3.RELEASE
> Update the dependency-management-plugin to work with Gradle 2.5

- src/main/java/io/github/robwin/swagger2markup/builder/document/OverviewDocument.java
- src/test/java/io/github/robwin/swagger2markup/Swagger2MarkupConverterTest.java
- src/test/resources/yaml/swagger_should_contain_uri_scheme.yaml
- src/test/resources/yaml/swagger_should_not_contain_uri_scheme.yaml
The URI scheme header should not be rendered if none of host, schemes or basePath are set. Only render it if one or more of the above are used.
> Do not render URI scheme if none of host, schemes or basePath are set

- README.adoc
The list of alternative publishing libraries was missleading in the sense it lead me to believe that I could use this library to generate AsciiDoc or Markdown, which would work in all of the listed documentation hosting services / open source projects templates.
I feel the alterations better reflect the intensions of the list.
> Updated readme to better reflect alternatives listing

- src/main/java/io/github/swagger2markup/internal/document/builder/PathsDocumentBuilder.java
- src/test/resources/expected/asciidoc/default/paths.adoc
- src/test/resources/expected/asciidoc/enums/paths.adoc
- src/test/resources/expected/asciidoc/examples/paths.adoc
- src/test/resources/expected/asciidoc/generated_examples/paths.adoc
- src/test/resources/expected/asciidoc/group_by_tags/paths.adoc
- src/test/resources/expected/asciidoc/idxref/paths.adoc
- src/test/resources/expected/asciidoc/inline_schema/paths.adoc
- src/test/resources/expected/asciidoc/inline_schema_flat_body/paths.adoc
- src/test/resources/expected/asciidoc/maps/paths.adoc
- src/test/resources/expected/asciidoc/polymorphism/paths.adoc
- src/test/resources/expected/asciidoc/response_headers/paths.adoc
- src/test/resources/expected/asciidoc/toFile/outputFile.adoc
Hello!
Swagger2Markup version: 1.0.0
Problem description:
Generated Asciidoc files have too narrow columns for 'HTTP Code' (section Responses) and 'Type' (section Parameters). This results in a bit badly generated output in both HTML and PDF. While HTML breaks line after a word (which looks OK), PDF breaks line e.g. HT-TP Cod-e, which does not look good. I have played a bit with the code and changed places where tables are defined. I just extended with on 1st column and respectively narrowed biggest column.
Screenshots below show generated html and pdf _before_ and _after_ modifications:
*#* HTML _before_
*#* HTML _after_
*#* PDF _before_
*#* PDF _after_
> 1st column in table extended width in order to avoid text wrapping

- src/docs/asciidoc/usage_guide.adoc
- src/main/java/io/github/swagger2markup/Swagger2MarkupConfig.java
- src/main/java/io/github/swagger2markup/Swagger2MarkupProperties.java
- src/main/java/io/github/swagger2markup/builder/Swagger2MarkupConfigBuilder.java
- src/main/java/io/github/swagger2markup/internal/document/builder/PathsDocumentBuilder.java
- src/main/resources/io/github/swagger2markup/config/default.properties
- src/test/java/io/github/swagger2markup/builder/Swagger2MarkupConfigBuilderTest.java
- src/test/resources/config/config.properties
As discussed in Gerrit, this change adds a new property "pathSecuritySectionEnabled" (default: true) to optionally disable the security section for every path element.
The main reason for this option is that the table in the section can grow large and doesn't provide useful information if it always looks the same (my example requires some HTTP Headers for authentication which are repeated over and over for every path)
> new property "pathSecuritySectionEnabled" (default: true)

- src/test/resources/expected/asciidoc/instagram/overview.adoc
The fenced code block in the original specification was previously
converted to something resembling an inline code element, while
the new output now contains an actual code block.
This closes #168.
> Fixes expected output of testSwagger2AsciiDocConversionInstagram

- src/main/java/io/github/swagger2markup/internal/document/builder/MarkupDocumentBuilder.java
- src/main/java/io/github/swagger2markup/internal/utils/PropertyUtils.java
- src/test/resources/expected/asciidoc/default/definitions.adoc
- src/test/resources/expected/asciidoc/group_by_tags/definitions.adoc
- src/test/resources/expected/asciidoc/idxref/definitions.adoc
- src/test/resources/expected/asciidoc/polymorphism/definitions.adoc
- src/test/resources/expected/asciidoc/polymorphismAsIsOrdering/definitions.adoc
- src/test/resources/expected/asciidoc/toFile/outputFile.adoc
- src/test/resources/expected/asciidoc/validators/definitions.adoc
- src/test/resources/expected/markdown/default/definitions.md
- src/test/resources/expected/markdown/idxref/definitions.md
- src/test/resources/json/swagger_validators.json
Hi, swagger2markup currently _always_ formats min/max value as a decimal, which looks weird when the property is an integer. This PR formats the min/max for integers as integers and decimal for decimals.
> Updated min/max value to format correctly based on the data type

- src/main/java/io/github/swagger2markup/internal/document/builder/MarkupDocumentBuilder.java
- src/main/java/io/github/swagger2markup/internal/utils/PropertyUtils.java
- src/main/resources/io/github/swagger2markup/lang/labels_de.properties
- src/main/resources/io/github/swagger2markup/lang/labels_en.properties
- src/main/resources/io/github/swagger2markup/lang/labels_es.properties
- src/main/resources/io/github/swagger2markup/lang/labels_fr.properties
- src/main/resources/io/github/swagger2markup/lang/labels_ru.properties
- src/main/resources/io/github/swagger2markup/lang/labels_tr.properties
- src/main/resources/io/github/swagger2markup/lang/labels_zh.properties
- src/test/java/io/github/swagger2markup/AsciidocConverterTest.java
- src/test/resources/expected/asciidoc/validators/definitions.adoc
- src/test/resources/json/swagger_validators.json
As a follow up to #192, this PR adds support for exclusiveMin and exclusiveMax by changing the min/max label, i.e.
`exclusiveMinimum == false`: **Minimum value**
`exclusiveMinimum == true`: **Minimum value (exclusive)**
`exclusiveMaximum == false`: **Maximum value**
`exclusiveMaximum == true`: **Maximum value (exclusive)**
Inclusive is assumed to be the default, so there's no `(inclusive)` required.
> Added support for exclusiveMin and exclusiveMax

- src/main/java/io/github/swagger2markup/internal/component/ResponseComponent.java
Fix NPE for response headers with relative definitions
as reported https://github.com/Swagger2Markup/swagger2markup-maven-plugin/issues/31
> Fix NPE for response headers with relative definitions

- src/main/java/io/github/swagger2markup/internal/component/ParameterTableComponent.java
I noticed when I tried creating a markup file for OPERATION_DESCRIPTION_BEGIN, that the content was being inserted two places: right after the path's "Description", and right after the parameter table's "Parameters" title. It looks like it is just a case of the wrong Position enum being used for the parameters table component.
> Fix position reference for parameters table.

- src/main/java/io/github/swagger2markup/Swagger2MarkupConfig.java
- src/main/java/io/github/swagger2markup/Swagger2MarkupProperties.java
- src/main/java/io/github/swagger2markup/builder/Swagger2MarkupConfigBuilder.java
- src/main/resources/io/github/swagger2markup/config/default.properties
- src/test/java/io/github/swagger2markup/builder/Swagger2MarkupConfigBuilderTest.java
- src/test/resources/config/config.properties
Adds in the capability to have array valued properties. Mostly only affects extensions that may need this. It is disabled by default and should work the same as it currently does. Array values can be enabled by setting a separator character in the "swagger2markup.documentFolderSeparator" configuration attribute.
This is a dependency so that the dynamic content extension can be altered to support multiple source folders for each content folder. Pull request for it coming next.
> Multi-Valued Dynamic Content Folders

- src/main/java/io/github/swagger2markup/internal/utils/ExamplesUtil.java
- src/test/java/io/github/swagger2markup/internal/component/PathOperationComponentTest.java
- src/test/resources/component/path_operation_with_path_param_example.adoc
- src/test/resources/component/path_operation_with_query_param_example.adoc
- src/test/resources/yaml/swagger_petstore.yaml
The adoc output of a path' example always use the default value.For
example in the unit test:
* pets/{petId} use the path params `petId` with example 30, but the
output adoc rendered pets/0 (0 is the default value of int param)
* pets/{findByTags} use the query params `tags` with example adorable,
but the output adoc rendered "tags":"string" ("string" is the default
value of string param)
It should use the "x-example" of the swagger(also the method `example()`
of the swagger-core jar.
This is the first commit to fix this problem, which add the
unit test for it.
> Fix request path and query params' example support.

- src/main/java/io/github/swagger2markup/internal/component/PropertiesTableComponent.java
- src/test/resources/expected/asciidoc/basepathprefix/definitions.adoc
- src/test/resources/expected/asciidoc/generated_examples/definitions.adoc
Properties of type RefType are currently resolved as text and not as links.
For instance, in Swagger documentation all Examples of a ref will look like this: `<<_assignment>>` instead of [Assignment](#Assignment)
> Property refs are resolved as links and not as text

- build.gradle
- gradle/documentation.gradle
As promised the deprecated `org.ajoberstar.github-pages` is replaced with `org.ajoberstar.git-publish`.
See https://github.com/ajoberstar/gradle-git-publish#migrating-from-orgajoberstargithub-pages for details.
Most significant change is the authentication it now must be via env or system property. Left a comment in the build file.
> replace deprecated gh pages plugin

- src/main/java/io/github/swagger2markup/builder/Swagger2MarkupConfigBuilder.java
Move up the code that enables list delimiters so that it comes before any list properties are parsed.
The problem can be seen with a properties file containing the following.  This will throw an exception:
swagger2markup.listDelimiterEnabled=true
swagger2markup.pageBreakLocations=BEFORE_DEFINITION,BEFORE_OPERATION
> Fix list parsing in properties file

- src/main/java/io/github/swagger2markup/internal/component/PropertiesTableComponent.java
Optional examples will not always start in a new line if there is other content before the example but no optionalDefaultValue. 
For Example: You have an Pattern but no optional default value. Then the example will be in the same line as the pattern and have no white space between the pattern value and the example heading.
> make examples always start newline if there is other content in the same cell

- build.gradle
- src/main/java/io/github/swagger2markup/internal/adapter/PropertyAdapter.java
- src/main/java/io/github/swagger2markup/internal/component/ResponseComponent.java
- src/main/java/io/github/swagger2markup/internal/utils/ExamplesUtil.java
- src/main/java/io/github/swagger2markup/internal/utils/ModelUtils.java
By moving from swagger parser version 1.0.31 to 1.0.35, the double quoted text examples identified in issue #298 will be fixed.
> Resolve issue #298 - Move to latest swagger parser

- src/main/java/io/github/swagger2markup/internal/adapter/PropertyAdapter.java
- src/main/java/io/github/swagger2markup/internal/utils/ExamplesUtil.java
- src/test/java/io/github/swagger2markup/AsciidocConverterTest.java
- src/test/resources/expected/asciidoc/generated_examples_inline_response/definitions.adoc
- src/test/resources/expected/asciidoc/generated_examples_inline_response/overview.adoc
- src/test/resources/expected/asciidoc/generated_examples_inline_response/paths.adoc
- src/test/resources/expected/asciidoc/generated_examples_inline_response/security.adoc
- src/test/resources/yaml/swagger_examples_inline_response.yaml
* Handle untyped inlines - swagger parser no longer defaults untyped to object types
* Handle object inlines - generates a name based on method and response code
* Handle object inlines with titles - generates a name from the title
> Generate examples for inline responses - Issue #313

- src/main/java/io/github/swagger2markup/Swagger2MarkupConfig.java
- src/main/java/io/github/swagger2markup/Swagger2MarkupProperties.java
- src/main/java/io/github/swagger2markup/builder/Swagger2MarkupConfigBuilder.java
- src/main/java/io/github/swagger2markup/internal/document/PathsDocument.java
- src/main/java/io/github/swagger2markup/internal/utils/PathUtils.java
- src/main/resources/io/github/swagger2markup/config/default.properties
- src/test/java/io/github/swagger2markup/builder/Swagger2MarkupConfigBuilderTest.java
- src/test/java/io/github/swagger2markup/internal/component/SecuritySchemeComponentTest.java
Sometimes, we need to merge the api docs of several services into one, which requires the full path of each api, including the hostname. I found that this feature is not currently supported, so this pr exists.
In order to get a complete api path, you need to do the following:
1.modify swagger configuration
new Docket().host("your own hostname")
2. add swagger2markup configuration, the default value is false
swagger2markup.hostnameEnabled=true
Thanks for spending time reviewing this pr, looking forward to feedback.
> add hostname in uri section of every operation, it is configurable.

- swagger2markup-asciidoc/src/main/java/io/github/swagger2markup/adoc/AsciidocConverter.java
- swagger2markup-swagger-v3/src/main/java/io/github/swagger2markup/internal/component/EncodingComponent.java
- swagger2markup-swagger-v3/src/main/java/io/github/swagger2markup/internal/component/ExamplesComponent.java
- swagger2markup-swagger-v3/src/main/java/io/github/swagger2markup/internal/component/MediaContentComponent.java
- swagger2markup-swagger-v3/src/main/java/io/github/swagger2markup/internal/component/MediaTypeExampleComponent.java
- swagger2markup-swagger-v3/src/main/java/io/github/swagger2markup/internal/component/ResponseComponent.java
- swagger2markup-swagger-v3/src/main/java/io/github/swagger2markup/internal/component/SchemaComponent.java
- swagger2markup-swagger-v3/src/main/java/io/github/swagger2markup/internal/helper/OpenApiHelpers.java
- swagger2markup-swagger-v3/src/test/resources/asciidoc/petstore.adoc
- swagger2markup-swagger-v3/src/test/resources/asciidoc/simple.adoc
- swagger2markup-swagger-v3/src/test/resources/open_api/petstore.yaml
#388 OpenApi 3.0 example object support
Add support for `content` object for request and responses
> OpenApi 3.0 example object support

- swagger2markup/src/main/java/io/github/swagger2markup/internal/component/PathOperationComponent.java
- swagger2markup/src/test/java/io/github/swagger2markup/AsciidocConverterTest.java
- swagger2markup/src/test/resources/expected/asciidoc/examples_suffix/definitions.adoc
- swagger2markup/src/test/resources/expected/asciidoc/examples_suffix/overview.adoc
- swagger2markup/src/test/resources/expected/asciidoc/examples_suffix/paths.adoc
- swagger2markup/src/test/resources/expected/asciidoc/examples_suffix/security.adoc
- swagger2markup/src/test/resources/json/swagger_examples_suffix.json
> Added support for MIME types with structured syntax suffixes

- openapi2markup/src/main/java/io/github/swagger2markup/extension/DefinitionsDocumentExtension.java
- openapi2markup/src/main/java/io/github/swagger2markup/extension/OverviewDocumentExtension.java
- swagger2markup/src/main/java/io/github/swagger2markup/internal/utils/pathexamples/BasicPathExample.java
- swagger2markup/src/main/java/io/github/swagger2markup/internal/utils/pathexamples/CurlPathExample.java
- swagger2markup/src/main/java/io/github/swagger2markup/internal/utils/pathexamples/InvokeWebRequestPathExample.java
- swagger2markup/src/main/java/io/github/swagger2markup/internal/utils/pathexamples/PathExample.java
- swagger2markup/src/main/java/io/github/swagger2markup/internal/utils/pathexamples/UtilityPathExample.java
Fix Javadoc, added missing parameters and replaced with valid html.
No idea how the Travis builds passed, but local builds with Oracle JDK 8 failed due to javadoc errors
> Fix Javadoc, added missing parameters and replaced with valid html
